"""create tes daily market table

Revision ID: 7960d971120e
Revises: 
Create Date: 2026-09-21 19:31:00.175938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7960d971120e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tes_daily_market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('nominal_volume_cop_mn', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('open_yield', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('yield_at_min_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('avg_yield', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('yield_at_max_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('close_yield', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'security_id', name='uq_tes_daily_market_date_security')
    )
    op.create_index(op.f('ix_tes_daily_market_maturity_date'), 'tes_daily_market', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_tes_daily_market_security_id'), 'tes_daily_market', ['security_id'], unique=False)
    op.create_index(op.f('ix_tes_daily_market_trade_date'), 'tes_daily_market', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tes_daily_market_trade_date'), table_name='tes_daily_market')
    op.drop_index(op.f('ix_tes_daily_market_security_id'), table_name='tes_daily_market')
    op.drop_index(op.f('ix_tes_daily_market_maturity_date'), table_name='tes_daily_market')
    op.drop_table('tes_daily_market')
    # ### end Alembic commands ###
